### ISSUE TITLE
App run event wording is slightly broken

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-scalingo#325] opened 2023-03-29 16:13 UTC
```
 emichon@biniou  ~/Documents/Scalingo  scalingo --app biniou timeline
[...]
* Wed Mar 29 2023 15:42:11 - Run             - bashone-off container with command '' <etiennem (etienne@scalingo.com)>
[...]
```

**Comment by ipfaze** [comment] 2023-07-06 14:01
Duplicate of #326

**Closed by ipfaze** 2023-07-06 14:01 UTC
Labels: low, customer impact
